---
- name: EL...
  when: ansible_os_family == 'RedHat'
  include: EL.yml

- name: Debian...
  when: ansible_os_family == 'Debian'
  include: Debian.yml

- name: start chronos service
  service: name=chronos enabled=yes state=started
  
